In [12]:
from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer

In [13]:
import pandas as pd

In [14]:
df=pd.read_csv(r'C:\Users\Legion\Desktop\FinalYearProject\News.csv')
df.head(3)

,Date,article_title,article,source_name,source_link,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 205,Unnamed: 206,Unnamed: 207,Unnamed: 208,Unnamed: 209,Unnamed: 210,Unnamed: 211,Unnamed: 212,Unnamed: 213,Unnamed: 214
0,2024-03-29 08:41:00+00:00,Warren Buffett Is Raking In $4.36 Billion in A...,"For nearly 60 years, Berkshire Hathaway (NYSE:...",Yahoo Finance,https://finance.yahoo.com/quote/AAPL/news/warr...,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2024-03-29 08:09:27+00:00,Huawei Profit Surges as It Takes Share From Ap...,(Bloomberg) -- Huawei Technologies Co. sustain...,Yahoo Finance,https://finance.yahoo.com/quote/AAPL/news/huaw...,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2024-03-29 04:22:06+00:00,20 Countries that Receive the Most Foreign Dir...,"In this article, we will look at 20 countries ...",Yahoo Finance,https://finance.yahoo.com/quote/AAPL/news/20-c...,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [15]:

sentiments = SentimentIntensityAnalyzer()


positive_scores = []
negative_scores = []
neutral_scores = []
compound_scores = []


for article in df["article"]:
    scores = sentiments.polarity_scores(article)
    positive_scores.append(scores["pos"])
    negative_scores.append(scores["neg"])
    neutral_scores.append(scores["neu"])
    compound_scores.append(scores["compound"])


df["Positive"] = positive_scores
df["Negative"] = negative_scores
df["Neutral"] = neutral_scores
df["Compound"] = compound_scores

In [16]:
df.head(3)

,Date,article_title,article,source_name,source_link,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 209,Unnamed: 210,Unnamed: 211,Unnamed: 212,Unnamed: 213,Unnamed: 214,Positive,Negative,Neutral,Compound
0,2024-03-29 08:41:00+00:00,Warren Buffett Is Raking In $4.36 Billion in A...,"For nearly 60 years, Berkshire Hathaway (NYSE:...",Yahoo Finance,https://finance.yahoo.com/quote/AAPL/news/warr...,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.131,0.035,0.834,0.9993
1,2024-03-29 08:09:27+00:00,Huawei Profit Surges as It Takes Share From Ap...,(Bloomberg) -- Huawei Technologies Co. sustain...,Yahoo Finance,https://finance.yahoo.com/quote/AAPL/news/huaw...,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.086,0.060,0.854,0.9273
2,2024-03-29 04:22:06+00:00,20 Countries that Receive the Most Foreign Dir...,"In this article, we will look at 20 countries ...",Yahoo Finance,https://finance.yahoo.com/quote/AAPL/news/20-c...,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.090,0.011,0.899,0.9995

In [17]:
score = df["Compound"].values
sentiment = []
for i in score:
    if i >= 0.05 :
        sentiment.append('Positive')
    elif i <= -0.05 :
        sentiment.append('Negative')
    else:
        sentiment.append('Neutral')
df["Sentiment"] = sentiment

In [18]:
df.head(5)

,Date,article_title,article,source_name,source_link,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 210,Unnamed: 211,Unnamed: 212,Unnamed: 213,Unnamed: 214,Positive,Negative,Neutral,Compound,Sentiment
0,2024-03-29 08:41:00+00:00,Warren Buffett Is Raking In $4.36 Billion in A...,"For nearly 60 years, Berkshire Hathaway (NYSE:...",Yahoo Finance,https://finance.yahoo.com/quote/AAPL/news/warr...,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0.131,0.035,0.834,0.9993,Positive
1,2024-03-29 08:09:27+00:00,Huawei Profit Surges as It Takes Share From Ap...,(Bloomberg) -- Huawei Technologies Co. sustain...,Yahoo Finance,https://finance.yahoo.com/quote/AAPL/news/huaw...,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0.086,0.060,0.854,0.9273,Positive
2,2024-03-29 04:22:06+00:00,20 Countries that Receive the Most Foreign Dir...,"In this article, we will look at 20 countries ...",Yahoo Finance,https://finance.yahoo.com/quote/AAPL/news/20-c...,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0.090,0.011,0.899,0.9995,Positive
3,2024-03-29 01:33:10+00:00,20 Countries with the Lowest Homeless Populati...,"In this article, we will be navigating through...",Yahoo Finance,https://finance.yahoo.com/quote/AAPL/news/20-c...,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0.053,0.090,0.857,-0.9964,Negative
4,2024-03-28 21:11:33+00:00,Q1 2024 Takeaways: The rise and fall of the Ma...,"As the first quarter of 2024 draws to a close,...",Yahoo Finance,https://finance.yahoo.com/quote/AAPL/video/q1-...,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0.158,0.027,0.815,0.9997,Positive