In [1]:
from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer

In [2]:
import pandas as pd

In [3]:
df=pd.read_csv(r'C:\Users\Legion\Desktop\FinalYearProject\data\NewsWithStockPrice.csv')
df.head(3)

,Date,article_title,article,source_name,source_link,stock_price,stock_price_after_30_mins,change_percentage,label
0,2024-04-10 19:15:00,US government's Apple antitrust suit gets new ...,By Mike Scarcella(Reuters) - The U.S. Justice ...,Yahoo Finance,https://finance.yahoo.com/quote/AAPL/news/us-g...,168.035004,168.250000,0.127947,1
1,2024-04-10 17:00:00,Elon Musk Challenges Alphabet With Tesla's Rob...,In a significant week for the autonomous vehic...,Yahoo Finance,https://finance.yahoo.com/quote/AAPL/news/elon...,168.013397,168.420395,0.242241,1
2,2024-04-10 14:50:00,"Apple, TSMC, Super Micro Computer, AMD, and Ot...",Alibaba co-founder Jack Ma boosts company mora...,Yahoo Finance,https://finance.yahoo.com/quote/AAPL/m/dda4d5b...,167.820007,168.156906,0.200750,1

In [4]:

sentiments = SentimentIntensityAnalyzer()


positive_scores = []
negative_scores = []
neutral_scores = []
compound_scores = []


for article in df["article"]:
    scores = sentiments.polarity_scores(article)
    positive_scores.append(scores["pos"])
    negative_scores.append(scores["neg"])
    neutral_scores.append(scores["neu"])
    compound_scores.append(scores["compound"])


df["Positive"] = positive_scores
df["Negative"] = negative_scores
df["Neutral"] = neutral_scores
df["Compound"] = compound_scores

In [5]:
df.head(3)

,Date,article_title,article,source_name,source_link,stock_price,stock_price_after_30_mins,change_percentage,label,Positive,Negative,Neutral,Compound
0,2024-04-10 19:15:00,US government's Apple antitrust suit gets new ...,By Mike Scarcella(Reuters) - The U.S. Justice ...,Yahoo Finance,https://finance.yahoo.com/quote/AAPL/news/us-g...,168.035004,168.250000,0.127947,1,0.066,0.081,0.853,0.0129
1,2024-04-10 17:00:00,Elon Musk Challenges Alphabet With Tesla's Rob...,In a significant week for the autonomous vehic...,Yahoo Finance,https://finance.yahoo.com/quote/AAPL/news/elon...,168.013397,168.420395,0.242241,1,0.107,0.028,0.865,0.9927
2,2024-04-10 14:50:00,"Apple, TSMC, Super Micro Computer, AMD, and Ot...",Alibaba co-founder Jack Ma boosts company mora...,Yahoo Finance,https://finance.yahoo.com/quote/AAPL/m/dda4d5b...,167.820007,168.156906,0.200750,1,0.176,0.000,0.824,0.5994

In [6]:
score = df["Compound"].values
sentiment = []
for i in score:
    if i >= 0.05 :
        sentiment.append('Positive')
    elif i <= -0.05 :
        sentiment.append('Negative')
    else:
        sentiment.append('Neutral')
df["Sentiment"] = sentiment

In [7]:
df.head(5)

,Date,article_title,article,source_name,source_link,stock_price,stock_price_after_30_mins,change_percentage,label,Positive,Negative,Neutral,Compound,Sentiment
0,2024-04-10 19:15:00,US government's Apple antitrust suit gets new ...,By Mike Scarcella(Reuters) - The U.S. Justice ...,Yahoo Finance,https://finance.yahoo.com/quote/AAPL/news/us-g...,168.035004,168.250000,0.127947,1,0.066,0.081,0.853,0.0129,Neutral
1,2024-04-10 17:00:00,Elon Musk Challenges Alphabet With Tesla's Rob...,In a significant week for the autonomous vehic...,Yahoo Finance,https://finance.yahoo.com/quote/AAPL/news/elon...,168.013397,168.420395,0.242241,1,0.107,0.028,0.865,0.9927,Positive
2,2024-04-10 14:50:00,"Apple, TSMC, Super Micro Computer, AMD, and Ot...",Alibaba co-founder Jack Ma boosts company mora...,Yahoo Finance,https://finance.yahoo.com/quote/AAPL/m/dda4d5b...,167.820007,168.156906,0.200750,1,0.176,0.000,0.824,0.5994,Positive
3,2024-04-10 14:33:00,"Apple Stock Has 33% Upside, According to 1 Wal...",Investors are worried over declining iPhone sa...,Yahoo Finance,https://finance.yahoo.com/quote/AAPL/news/appl...,167.339996,168.300003,0.573686,1,0.097,0.079,0.824,0.9252,Positive
4,2024-04-10 14:30:00,Gold rises to near record highs even as intere...,Gold is shining bright among investors even as...,Yahoo Finance,https://finance.yahoo.com/quote/AAPL/news/gold...,167.425003,168.110001,0.409137,1,0.156,0.033,0.811,0.9996,Positive