In [1]:
from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer

In [2]:
import pandas as pd

In [3]:
df=pd.read_csv(r'..\data\News.csv')
df.head(3)

,Date,article_title,article,source_name,source_link,ticker_symbol,Positive,Negative,Neutral,Compound,...,Unnamed: 211,Unnamed: 212,Unnamed: 213,Unnamed: 214,Unnamed: 215,Unnamed: 216,Unnamed: 217,Unnamed: 218,Unnamed: 219,Unnamed: 220
0,2024-05-15 01:02:37+00:00,Huawei flagship store surge in China signals s...,HONG KONG (Reuters) — Huawei is revamping its ...,Yahoo Finance,https://finance.yahoo.com/news/huawei-flagship...,AAPL,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2024-05-15 01:02:37+00:00,"Huawei flagship store openings surge in China,...",HONG KONG (Reuters) — Huawei is revamping its ...,Yahoo Finance,https://finance.yahoo.com/news/huawei-flagship...,AAPL,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2024-05-15 01:00:00+00:00,FOCUS-Huawei flagship store surge in China sig...,*Huawei has opened four flagship stores in Chi...,Yahoo Finance,https://finance.yahoo.com/news/focus-huawei-fl...,AAPL,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:

sentiments = SentimentIntensityAnalyzer()


positive_scores = []
negative_scores = []
neutral_scores = []
compound_scores = []


for article in df["article"]:
    scores = sentiments.polarity_scores(article)
    positive_scores.append(scores["pos"])
    negative_scores.append(scores["neg"])
    neutral_scores.append(scores["neu"])
    compound_scores.append(scores["compound"])


df["Positive"] = positive_scores
df["Negative"] = negative_scores
df["Neutral"] = neutral_scores
df["Compound"] = compound_scores

In [5]:
score = df["Compound"].values
sentiment = []
for i in score:
    if i >= 0.5 :
        sentiment.append('Positive')
    elif i <= -0.5 :
        sentiment.append('Negative')
    else:
        sentiment.append('Neutral')
df["Sentiment"] = sentiment

In [6]:
df

,Date,article_title,article,source_name,source_link,ticker_symbol,Positive,Negative,Neutral,Compound,...,Unnamed: 211,Unnamed: 212,Unnamed: 213,Unnamed: 214,Unnamed: 215,Unnamed: 216,Unnamed: 217,Unnamed: 218,Unnamed: 219,Unnamed: 220
0,2024-05-15 01:02:37+00:00,Huawei flagship store surge in China signals s...,HONG KONG (Reuters) — Huawei is revamping its ...,Yahoo Finance,https://finance.yahoo.com/news/huawei-flagship...,AAPL,0.061,0.028,0.911,0.9744,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2024-05-15 01:02:37+00:00,"Huawei flagship store openings surge in China,...",HONG KONG (Reuters) — Huawei is revamping its ...,Yahoo Finance,https://finance.yahoo.com/news/huawei-flagship...,AAPL,0.061,0.028,0.911,0.9744,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2024-05-15 01:00:00+00:00,FOCUS-Huawei flagship store surge in China sig...,*Huawei has opened four flagship stores in Chi...,Yahoo Finance,https://finance.yahoo.com/news/focus-huawei-fl...,AAPL,0.062,0.027,0.911,0.9769,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2024-05-14 18:18:09+00:00,Apple touts stopping $1.8B in App Store fraud ...,Apple released new data about anti-fraud measu...,Yahoo Finance,https://finance.yahoo.com/news/apple-touts-sto...,AAPL,0.056,0.152,0.792,-0.9977,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2024-05-14 17:37:36+00:00,Google I/O Expected to Highlight Potential Gem...,Google I/O Expected to Highlight Potential Gem...,Yahoo Finance,https://finance.yahoo.com/news/google-o-expect...,AAPL,0.375,0.000,0.625,0.7783,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1113,2024-03-05 16:59:20+00:00,Apple Stock Gloom Deepens as Pressure to Show ...,(Bloomberg) -- Apple Inc.’s move to shutter it...,Yahoo Finance,https://finance.yahoo.com/quote/AAPL/news/appl...,AAPL,0.055,0.051,0.894,-0.0880,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1114,2024-03-05 16:55:49+00:00,What the shakeup in Magnificent 7 stocks means...,Stock market indices have been propped up on t...,Yahoo Finance,https://finance.yahoo.com/quote/AAPL/video/sha...,AAPL,0.118,0.028,0.854,0.9988,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1115,2024-03-05 16:46:00+00:00,Alphabet (GOOGL) Enhances Google Maps With New...,Alphabet’s GOOGL Google is gaining strong mome...,Yahoo Finance,https://finance.yahoo.com/quote/AAPL/news/alph...,AAPL,0.171,0.000,0.829,0.9982,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1116,2024-03-05 16:43:00+00:00,"Why Apple Stock Keeps Dropping, and What Could...","Apple stock is in the red this year, so Wall S...",Yahoo Finance,https://finance.yahoo.com/quote/AAPL/m/c76aec8...,AAPL,0.000,0.038,0.962,-0.4767,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1117,2024-03-05 16:27:00+00:00,Apple iPhone Sales Are Slipping in China. The ...,Weakness in China is the latest sign that Appl...,Yahoo Finance,https://finance.yahoo.com/quote/AAPL/m/d6d45fc...,AAPL,0.000,0.212,0.788,-0.6249,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
df.to_csv(r'..\data\News.csv',index=False)